### ISSUE TITLE
Extend Sequence with parseJson method

### ISSUE THREAD

**Issue by AlesTsurko** [IoLanguage/io#403]
There is `asJson` for Map, but there is no a reverse method.
I could add `parseJson` (or `jsonToMap`?) to Sequence using this library (only one exposed method, no dependencies, the implementation is 260 LOC): https://github.com/kr/json
That would be lightweight (and native) alternative to Yajl.
@stevedekorte what do you think?

**Comment by stevedekorte** [comment]
Sounds great.

**Comment by AlesTsurko** [comment]
ok, then I'll do it.

**Comment by AlesTsurko** [comment]
Done, but I used this library instead: https://github.com/kgabis/parson
It's also very lightweight, but a lot better.
The changes will be in the PR with the addons-related changes.
