### ISSUE TITLE
Unexpected behavior with a message without selector or symbol.

### ISSUE THREAD

**Issue by migueltk** [IoLanguage/io#405]
I use the version '20110905' of Io in Ubuntu 18.04. In interactive mode when I evaluate;

```
Io> 4
==> 4
```

The result is the expected '4', I understand that when 'Io' receives a message where the symbol is a literal, it simply returns this as a result. Another example;

```
Io> 4 5
==> 5
```

OR

```
Io> "hello"
==> hello
```

When I enter the expression (4), I understand that 'Io' receives a message without a selector, the message only has one argument. 'Io' evaluates the expression in parentheses and returns the result.

```
Io> (4)
==> 4
```

The problem, I do not understand the evaluation of the expression '4 (5)', 'Io' returns 4;

```
Io> 4 (5)
==> 4
```

I understand that it should return '5', first evaluate the literal 4 and return this as the receiver of the rest of the message, 4 as the receiver receives the message (5) and should return the evaluation of the expression in parentheses whose result is 5.

**Comment by stevedekorte** [comment]
Hi Miguel, Sorry for the delay responding.

A handy trick to see what the parser is doing is to run the expression through the message():

Io> message(4)
==> 4

Io> message(4 (5))
==> 4(5)

So it looks like the ()s after the 4 are treated as argument passing parens and not expression boundary parens. 

Part of the confusion here may be that, unlike other languages, Io's parse tree only has one type (a Message). So things like literals which would have been special types in other languages, are just message tokens in Io, which get composed into a tree of message objects. Io implements literals by having a cachedResult value which the parse sets on those message objects which skips sending a message and just returns the cacheResult referenced object. For example:

Io> message(1) doInContext(Lobby)
==> 1
Io> message(1) setCachedResult(2) doInContext(Lobby)
==> 2

Support for ()s being used outside of arguments is a bit of a hack which has it compile to a message with an empty name and the contents of the ()s as the argument. The empty name slot on Object is set to be the evalArg() method.

So if you wanted to keep them separate you could do:

Io>  4 evalArg(5)
==> 5

As this prevents the parens as being treated as arguments and evaluated as they would if they started the expression.

Io> message(4 evalArg(5))
==> 4 evalArg(5)

**Comment by migueltk** [comment]
Hello Steve, we are all busy, thanks for answering.

Just a couple of questions "I hope I'm not too insistent";

**1**. Io accepts the message;

```
Io> (2 + 3)
==> 5
```
but I observe the grammar;

```
expression :: = {message | sctpad}
message :: = [wcpad] symbol [scpad] [arguments]
arguments :: = Open [argument [{Comma argument}]] Close
argument :: = [wcpad] expression [wcpad]
```
for this to be possible, should not 'symbol' be optional ?, so that;

`message :: = [wcpad] [symbol] [scpad] [arguments]`

**2**. Io accepts and responds;

```
Io> (2 + 3, 4-1)
==> 5
```
I understand that Object_evalArg () only evaluates the first argument, is that so? What's the point of this? I dare to suggest this other grammar;

```
expression :: = {message | sctpad}
message :: = [wcpad] Open expression Close | symbol [scpad] [arguments]
arguments :: = Open [argument [{Comma argument}]] Close
argument :: = [wcpad] expression [wcpad]
```

that is, ("(" expression ")" | symbol [arguments]), where the parentheses group alternatives.

**Comment by stevedekorte** [comment]
The purpose of evalArg() is to eval expressions such as those in isolated parens.

I like that idea and it would work, but let's say we had it and did:

```
  String concat := method(s, self ..(s))

  "a" concat("b") // would return "ab"
  "a" concat ("b") // would create the string "anil" and return "b"
```

You can imagine how this might play out in lots of other situations.
Would this behavior produce less or more frustration? I'm not sure. What do you think?

Maybe you could try adding this rule and seeing if it produced any errors on the existing code base. If not, then that might be a good indication that it's rarely an issue and we could add it.
