### ISSUE TITLE
Build error in msys2 (mingw64 mode)

### ISSUE THREAD

**Issue by zyppe** [IoLanguage/io#418]
The same error is "  __attribute_used__ = { 0x7ff8000000000000 };"
**I used gcc 7.3.0 cmake 3.12.0.**
E:/msys64/home/heche/io/libs/iovm/source/IoNumber.h:27:2: error: expected '=',  ,', ';', 'asm' or '__attribute__' before '__attribute_used__'
  __attribute_used__ = { 0x7ff8000000000000 };
  ^~~~~~~~~~~~~~~~~~
In file included from E:/msys64/home/heche/io/libs/iovm/source/IoBlock.c:14:0:
E:/msys64/home/heche/io/libs/iovm/source/IoNumber.h:27:2: error: expected '=',  ,', ';', 'asm' or '__attribute__' before '__attribute_used__'
  __attribute_used__ = { 0x7ff8000000000000 };
  ^~~~~~~~~~~~~~~~~~
In file included from E:/msys64/home/heche/io/libs/iovm/source/IoCoroutine.c:14:0:
E:/msys64/home/heche/io/libs/iovm/source/IoNumber.h:27:2: error: expected '=',  ,', ';', 'asm' or '__attribute__' before '__attribute_used__'
  __attribute_used__ = { 0x7ff8000000000000 };
  ^~~~~~~~~~~~~~~~~~
In file included from E:/msys64/home/heche/io/libs/iovm/source/IoCollector.c:27:0:
E:/msys64/home/heche/io/libs/iovm/source/IoNumber.h:27:2: error: expected '=',  ,', ';', 'asm' or '__attribute__' before '__attribute_used__'
  __attribute_used__ = { 0x7ff8000000000000 };
  ^~~~~~~~~~~~~~~~~~
In file included from E:/msys64/home/heche/io/libs/iovm/source/IoCompiler.c:10: :
E:/msys64/home/heche/io/libs/iovm/source/IoNumber.h:27:2: error: expected '=',  ,', ';', 'asm' or '__attribute__' before '__attribute_used__'
  __attribute_used__ = { 0x7ff8000000000000 };
  ^~~~~~~~~~~~~~~~~~
In file included from E:/msys64/home/heche/io/libs/iovm/source/IoDate.c:13:0:
E:/msys64/home/heche/io/libs/iovm/source/IoNumber.h:27:2: error: expected '=',  ,', ';', 'asm' or '__attribute__' before '__attribute_used__'
  __attribute_used__ = { 0x7ff8000000000000 };
  ^~~~~~~~~~~~~~~~~~

**Comment by AlesTsurko** [comment]
Looks like your compiler considering it a syntax error.
@stevedekorte what's can be wrong here?
https://github.com/IoLanguage/io/blob/master/libs/iovm/source/IoNumber.h#L26

**Comment by stevedekorte** [comment]
I'm not sure. I don't recall adding that ifdef. Try commenting it out to get more clues?

**Comment by AlesTsurko** [comment]
This code has been introduced in this commit: https://github.com/IoLanguage/io/commit/a3320e2a5e865a5ae17086895e9026cfbea8fae8#diff-e0cb6f4d51369242e4d1bef3bb5c3f3b
@yangfl could you help?

**Comment by AlesTsurko** [comment]
@aiwonanjing, @yangfl has made some changes. Could you check it out now?
