### ISSUE TITLE
Website is down?

### ISSUE THREAD

**Issue by exikyut** [IoLanguage/io#432]
I'm not sure if the website offers a forum, contact details or a chatroom, since it's down, so I thought I'd poke in here.

My local browser is saying isup.me says the site is down, iolanguage.org is NXDOMAIN, and `whois` says the site expires in 2020. So the domain is okay.

It \_looks\_ like something's broken, *possibly* at Nearly Free Speech, or more specifically to do with the iolanguage site itself.

Local `dig` queries return nothing - not A, not AAAA, not ANY, not TXT.

But I after lots of clicking around in digwebinterface I came up with https://www.digwebinterface.com/?hostnames=iolanguage.org&type=A&showcommand=on&colorize=on&stats=on&sort=on&norecursive=on&compare=on&location=on&useresolver=8.8.4.4&ns=all&nameservers=, which I *think* is showing me some old/cached views of some probably(?)-working A and other records. I saved the query results I got at https://pastebin.com/AUnTpdxd which will last 6 months.

**Comment by acook** [comment]
Hmm, looks up to me. Maybe it was temporary?

**Comment by stevedekorte** [comment]
Thanks for the report. I just needed to put some funds in my nearly free speech account.
