### ISSUE TITLE
Warnings & error when running `sudo make install` to build from source in zsh, MacOS 10.15.6

### ISSUE THREAD

**Issue by jeffelrod** [IoLanguage/io#436]
After running `make` in the `build/` directory to start the process of building from source in MacOS 10.15.6/zsh (outlined [here](https://github.com/IoLanguage/io#linux-build-instructions)), I attempt to run `sudo make install`. I get back the following warnings/error (some additional context provided):
```
-> Install Eerie
 - Fetching Eerie
 - Resolving dependencies for Eerie
-> Install Kano
 - Fetching Kano
 - Resolving dependencies for Kano
 - Installing Kano...
-> Install Docio
 - Fetching Docio
 - Resolving dependencies for Docio
-> Install Markdown
 - Fetching Markdown
 - Resolving dependencies for Markdown
 - Installing Markdown...
 - Compiling source files...
mkdir -p _build/headers
 ! Last command exited with the following error:
 !
 ! source/IoMarkdown.c:96:69: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'mkd_flag_t *' (aka 'void *') [-Wint-conversion]
    document = mkd_string(UTF8CSTRING(input), IoSeq_rawSize(input), flags);
                                                                    ^~~~~
/Users/jelrod/.eerie/env/_base/addons/Markdown/source/discount/mkdio.h:76:46: note: passing argument to parameter here
MMIOT *mkd_string(const char*,int,mkd_flag_t*); /* assemble input from a buffer */
                                             ^
source/IoMarkdown.c:97:27: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'mkd_flag_t *' (aka 'void *') [-Wint-conversion]
    mkd_compile(document, flags);
                          ^~~~~
/Users/jelrod/.eerie/env/_base/addons/Markdown/source/discount/mkdio.h:91:36: note: passing argument to parameter here
int mkd_compile(MMIOT*, mkd_flag_t*);
                                   ^
source/IoMarkdown.c:102:5: error: implicit declaration of function 'mkd_deallocate_tags' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    mkd_deallocate_tags();
    ^
2 warnings and 1 error generated.
```
I had initially installed `io` using [Homebrew](https://formulae.brew.sh/formula/io#default), but found I couldn't install any addons since the Homebrew installation doesn't include `eerie`.

**Comment by ales-tsurko** [comment]
The homebrew version is outdate. It's pre-Eerie and comes with all the addons.

As for the Markdown addon compilation, if you follow the installation instructions and the issue still exists, please open an issue in the [Eerie repo](https://github.com/IoLanguage/eerie/issues).

**Comment by jeffelrod** [comment]
@ales-tsurko Will do; I'm also trying to set up Eerie separately following the [instructions](https://github.com/IoLanguage/eerie#installing) provided in its repo and encountering a different error, so I figured it'd be best to raise the issue I'm encountering in the documented Io build process here, and to raise the issue I'm encountering in the documented Eerie build process there.

**Comment by jeffelrod** [comment]
This was an issue with the Markdown plugin in Eerie; it's now resolved for Eerie & should work here as well.
