### ISSUE TITLE
sudo make install fails on CenOS in the Install Eerie part

### ISSUE THREAD

**Issue by halloleo** [IoLanguage/io#442]
I am trying to install the current version of Io. For this I have clone the repo and the build succeeds. However on `sudo make install` I get the following error output:

```
------------Installing Eerie------------
-> Install Eerie
 - Fetching Eerie
 ! Last command exited with the following error:
 ! 
 ! Cloning into '/root/.eerie/env/_base/addons/Eerie'...
fatal: unable to access 'https://github.com/IoLanguage/eerie.git/': SSL connect error
```

I am behind a proxy, so I figure that the Makefile tries to access the Internet and fails. I  have configured things that normal `git clone https://...` commands work in my shell. So, can I run the cloning command manually before I run `sudo make install`?

Also: I am _very_ concerned that the script wants to clone into `/root/.eerie/`. I run `sudo make install` as a normal user with a home directory like `/home/me`, so `/root/` as home can't be right. Can I set my home directory somehow as an option to the install process?

**Comment by ales-tsurko** [comment]
To compile without Eerie run cmake with `-DWITHOUT_EERIE=1` flag.

To install into /home, just install without `sudo` (i.e. `io setup.io` from Eerie's root).

**Comment by halloleo** [comment]
Thank you @ales-tsurko. Will try to install GitHub's Io first without Eerie, and then install Eerie in a 2nd step.

**Comment by halloleo** [comment]
I was successful installing Io without Eerie. So far so good - but then when installing Eerie things went wrong: see ["Syntax error near this location" on line 84 character 2432 on errie doc straight after install · Issue #35 · IoLanguage/eerie](https://github.com/IoLanguage/eerie/issues/35). I guess I can close this issue here though.
