### ISSUE TITLE
New Eerie version incompatible with addon system (needs agreement)

### ISSUE THREAD

**Issue by ales-tsurko** [IoLanguage/io#444]
I've been working on a new Eerie version since September, and now its API is done. There're a lot of improvements:

- stability and maintainability - fully refactored with good test coverage
- packages are scoped in a project (like `node_modules` in NPM). And there're still global packages
- packages now have versions, and it supports dependencies on specific version
- new modules system, which closes a package's stuff in a context and prevents a different version of a package from colliding
- basic debugger
- tests runner with basic glob-like parser (i.e. `eerie test "*Foo*"` will run all tests containing "Foo": FooBar, BarFoo, BarFooBar, etc.)
- native package builder command - it's now easier to develop packages with C code
- centralized database for addons, which is a simple git repo (so you could use your own private database). It's still possible to install a package not registered in the database
- package validator and releaser to make it easier to prepare a package for release
- API is fully documented
- colorful command line output :)

These things will also be ready when the new version of Eerie is released:

- usage guide
- update for Docio (documentation generator)
- better installation script

But there're breaking changes, which make new version of Eerie incompatible with the old addon API (you can still install packages as addons, though, if you wish). First, because of the package versions. Previously you could have only a single version of an addon, and it's imported globally. In the new version of Eerie we have modules, which have dependencies as their modules. Each module is a closed context (namespace). For example, I have a package A which have a dependency B. Package A has an object O and package B has an object P:

```Io
A hasSlot("O") # true
A hasSlot("B") # true - this is our dependency module and everything from this module is closed in its context
A B hasSlot("P") # true
A B Object hasSlot("P") # true 
A hasSlot("P") # false
A B hasSlot("O") # false
```

Io automatically loads Eerie, global packages (Eerie dependencies) and current working directory if it's a package. The top level package (the lowest common ancestor) is loaded in Lobby (still all its stuff closed in a context), but deeper dependencies are loaded in their own context.

Basically, previously if I had an addon it was global, and I just could start to use protos from this addon everywhere (or bring its context once, then all this stuff was available). Now I can use dependency only via its context/module. So previously I could use P from the B globally, now I can use it only in the context of the module, which has dependency B and only via the context of B (as I described earlier).

This system allows to use different versions. For example A has B@0.2.0 and C@0.1.0, but C@0.1.0 has B@0.1.0:

```Io
A hasSlot("B") # true
A hasSlot("C") # true
A C hasSlot("B") # true
# comparing versions of packages
A B package struct manifest version == A C B package struct manifest version # false
```

It also prevents stuff from colliding. For example, if there is a package with an object named "Foo" and another package with the same named object. Previously, either Io would crash or one of the packages would rewrite "Foo". Now they're isolated in its context and available only in it.

I need to update all addons to mirror this change. And the addons, which previously used stuff from their dependencies via global context obviously will not work with the new module system.

As Io is stuck in development, I think it's not very harmful. There're not much stuff in production and the old stuff is abandoned. Also, updating an addon to the new module system isn't hard to do. And it's still possible to use older version of addons and Io (thankfully to git). We need to go further.

I need an approval to do this. @stevedekorte

**Comment by stevedekorte** [comment]
Does the new system still allow addons to load transparently by referencing them?

**Comment by ales-tsurko** [comment]
Could you provide an example of what do you mean? Then I could also better explain how it worked related to the new system.

**Comment by stevedekorte** [comment]
For example, if you run this code:

digest := MD5 clone
digest appendSeq("this is a message")
out := digest md5String

Then, IIRC, MD5 addon is automatically/dynamically loaded.

**Comment by ales-tsurko** [comment]
Translating to the new system, it looks like this:

```Io
digest := MD5 MD5 clone
digest appendSeq("this is a message")
out := digest md5String
```

The first MD5 is the context, which contains the `Package` object (an object from Eerie containing all the information and methods needed to work with the package) and everything defined in the package. Everything inside MD5 available only via its context (i.e. `MD5 something`). And unavailable globally without referring the context.

For example, if I have some extension defined in MD5, like:

```Io
System do (
    test := "test"
)
```

When I'm outside of `MD5`:

```Io
System hasSlot("test") # false
```

But: 

```Io
MD5 System hasSlot("test") # true
```

The same is for the proto `MD5`. If I defined a proto:

```Io
MD5 := Object clone do (  
    test := "test"
    /*...*/ 
)
```

Then:

```Io
MD5 hasSlot("test") # false
```

But inside the module:

```Io
MD5 MD5 hasSlot("test") # true
```

Also, when I am the developer of MD5, I don't refer the context of my package, when I instantiated Io program in the package's directory. That means everywhere inside MD5:

```Io
System hasSlot("test") # true
MD5 hasSlot("test") # true
```
---
Still if I want to make my code work with the old system, I can do:

```Io
MD5 = MD5 MD5
```

See, for example, like I did it inside Eerie itself to be able to develop it with the old addon system:
https://github.com/IoLanguage/eerie/blob/develop/io/Logger.io#L16

But it's important, that things from the modules are available only via its context. So while previously, when you had an extension, you could bring it to the global context by referring the addon once, then now it's possible only via the context (i.e. `PackageName somethingFromThePackage`). And this prevents such issues as:

- you have a dependency with one version, but some of your dependencies depend on another version of the same package
- you have an object with the same name as a dependency has
- a dependency might define some extension for a core proto, which would break how it works for your program (or you might define an extension, which will break it for a dependency)

To better understand the difference, you can compare the implementation of the addon loader (`Addon load`) with Eerie's one: https://github.com/IoLanguage/eerie/blob/develop/io/Package.io#L309

**Comment by stevedekorte** [comment]
I would think: 

```
    MD5 System hasSlot("test") # true
    System hasSlot("test") # false
```

Is going to cause problems. For example, after loading MD5 we'll want to do things like 

`    
"some string" md5
`
But that string is not "in" MD5. It's a global symbol.

**Comment by ales-tsurko** [comment]
Yes, it's impossible outside MD5 context, but:

```Io
MD5 do ("some string" md5)
```

would work.

**Comment by ales-tsurko** [comment]
If you wish to define global extension in you module, it could be possible like this:

```Io
Lobby System do (
test := "test"
)
```

**Comment by ales-tsurko** [comment]
Also, to bring extension in your context, you may do:

```Io
System = MD5 System
```

**Comment by ales-tsurko** [comment]
Just checked and actually, if a thing already global (like `System`, `Sequence`, etc.), when you do something inside this context (`TheThing do ( ... )`), it's available for that globally as well. So this should be done differently to be available only in the context and my example with `System do` was wrong :) But everything else has tests for this and works as I described.

**Comment by stevedekorte** [comment]
Ok, it sound great other than the concerns we covered.

**Comment by ales-tsurko** [comment]
So you against it if it would be possible like [this](https://github.com/IoLanguage/io/issues/444#issuecomment-762420169) and/or [this](https://github.com/IoLanguage/io/issues/444#issuecomment-762421025) only (not in the global context by default)? Because that's how it would work, if there was no bug related to core protos (which I discovered here). Isn't that good to prevent the users from rewriting such things globally by default?

**Comment by stevedekorte** [comment]
I think it's ok as long as addons have a way to add to global context (as you mentioned), and we make sure all existing uses of the global context additions still work by using the that as needed (e.g. extending Sequence, Number, etc).

**Comment by ales-tsurko** [comment]
Hurray! So now I need just to fix the bug I discovered here and update something like 80 packages :)
