### ISSUE TITLE
Embedding Io

### ISSUE THREAD

**Issue by nikneym** [IoLanguage/io#447]
Hi, I want to embed Io inside to my project but I've got some linker errors. am I missing a flag there?

`gcc main.c -lbasekit -liovmall
`

I ran this code to check if it works

```
#include <stdio.h>
#include "io/IoState.h"

int main(int argc, const char *argv[]) {
    IoState *self = IoState_new();
    IoState_init(self);
    IoState_doCString_(self, "writeln(\"hello world!\"");
    IoState_free(self);
    return 0;
}
```
the errors I got
![image](https://user-images.githubusercontent.com/4337696/113851176-e907d480-97a3-11eb-9a64-b40650ccec28.png)

I got the shared library installed at usr/local/lib

![image](https://user-images.githubusercontent.com/4337696/113849423-24a19f00-97a2-11eb-87f1-8bcf8dc13eac.png)

and header files at usr/local/include

![image](https://user-images.githubusercontent.com/4337696/113849539-4864e500-97a2-11eb-8aa0-7245d173da22.png)

**Comment by ales-tsurko** [comment]
`gcc main.c -lbasekit -liovmall -lm`?

**Comment by nikneym** [comment]
Ah, thank you. Works like a charm!
