### ISSUE TITLE
Does anyone compile it on M1 successfully? 

### ISSUE THREAD

**Issue by bondiano** [IoLanguage/io#451]
```Last 15 lines from /Users/bondiano/Library/Logs/Homebrew/io/02.make:
/tmp/io-20210601-6479-1mv49om/io-2017.09.06/libs/coroutine/source/asm.S:211:13: error: unexpected token in argument list
 lwz r0, 3*4(r3)
            ^
/tmp/io-20210601-6479-1mv49om/io-2017.09.06/libs/coroutine/source/asm.S:212:2: error: unrecognized instruction mnemonic
 mtxer r0
 ^
/tmp/io-20210601-6479-1mv49om/io-2017.09.06/libs/coroutine/source/asm.S:214:13: error: unexpected token in argument list
 lwz r3, 6*4(r3)
            ^
/tmp/io-20210601-6479-1mv49om/io-2017.09.06/libs/coroutine/source/asm.S:215:2: error: too few operands for instruction
 blr
 ^~~
make[2]: *** [libs/coroutine/CMakeFiles/coroutine.dir/source/asm.S.o] Error 1
make[1]: *** [libs/coroutine/CMakeFiles/coroutine.dir/all] Error 2
make: *** [all] Error 2```

**Comment by stevedekorte** [comment]
We might need to update the coroutine library. Maybe the ARM settings will work?

**Comment by bondiano** [comment]
@stevedekorte Please, could you help, how to run with compiler ARM settings?

**Comment by stevedekorte** [comment]
Now that I'm looking at it, I'm not sure we have ARM support. I haven't kept up with the changes to the build system, but the place to look is in: io/libs/coroutine/source/ . Might need to add an appropriate ARM ifdef within the APPLE ifdef. Can someone familiar with the ams.S code take a look at what we need to change for ARM?

**Comment by ales-tsurko** [comment]
Right-click -> Get info (or select and Cmd-I) Terminal.app, then enable "Open using Rosetta" option. Open the Terminal.app and follow the Io compilation instructions.

**Comment by bondiano** [comment]
@ales-tsurko, I still have the same problem after enable the "Open using Rosetta" option.

**Comment by ales-tsurko** [comment]
It should work. Try to remove the build directory, make it sure you use terminal in rosetta, etc.

**Comment by stevedekorte** [comment]
Any luck with this?

**Comment by bondiano** [comment]
Thx, yes, It helped.  I remove the build/ directory and repeat it all.

![image](https://user-images.githubusercontent.com/323479/125934565-15c4583a-08d4-4beb-8c1e-00e8dd8dd1d9.png)
