### ISSUE TITLE
No implement of function IoVMCodeInit in file IoState.c

### ISSUE THREAD

**Issue by 71USERX** [IoLanguage/io#457]
This problem cause a compile-time error when I try to compile source code of io with Visual Studio 2019(16.11)

**Comment by akluth** [comment]
How do you exactly build IO with Visual Studio 2019? Please provide as much information about the error/the compilation step as possible.

**Comment by 71USERX** [comment]
> How do you exactly build IO with Visual Studio 2019? Please provide as much information about the error/the compilation step as possible.
![io](https://user-images.githubusercontent.com/68045727/133977252-40f0a3eb-bcc9-490e-a472-ed41575ce5cc.png)
There isn't a implement for this function or VS didn't detected the implement.
I using the CMake 3.21.1 to generate vs solution from io-2017's source code.

**Comment by 71USERX** [comment]
> What exactly do you mean by "io-2017's source code"?
> 
> The preferred way to build Io under Windows is to use MinGW/MSYS2. Is this possible for you to use? I cannot reproduce your error locally because I get a bunch of others trying to compile it...

Thank you for help.
I build Io successfully by using MinGW.
(The "io-2017's source code" means this:
![ior2017](https://user-images.githubusercontent.com/68045727/134279396-3aac3754-a1bb-4948-a074-6ccb8a398aac.png)
I am a Chinese. My English is not good. This may have caused some misunderstandings....I feel sorry about it)

**Comment by akluth** [comment]
Do not feel sorry about it, your english is very good :-)

I'm glad that I could help. :-)
