### ISSUE TITLE
No way to convert from a binary string back to a number?

### ISSUE THREAD

**Issue by vaartis** [IoLanguage/io#459]
There's `Number asBinary`, but no way to convert this string back to a number. 

```
Io> 42 asBinary asBinaryNumber
==> 0

Io> 42 asBinary asBinarySignedInteger

  Exception: Sequence is 8 bytes but only conversion of 1, 2, or 4 bytes is supported
  ---------
  message 'asBinarySignedInteger' in 'Command Line' on line 1

Io> 42 asBinary asBinaryUnsignedInteger

  Exception: Sequence is 8 bytes but only conversion of 1, 2, or 4 bytes is supported
  ---------
  message 'asBinaryUnsignedInteger' in 'Command Line' on line 1
```

Am I missing something?

**Comment by vaartis** [comment]
```io
Sequence binaryAsDecimal := method(
    reversed := self reverse
    result := 0

    for(i, 0, reversed size - 1,
        numAt := reversed charAt(i) asNumber

        result = result + (numAt * (2 ** i))
    )

    result
)


Sequence charAt := method(i,
    exSlice(i, i + 1)
)

```

Well, I wrote a function for it but somthing like that should probably be available in the standard library,as well as a way to get a single character from a string (and not its numeric representation)

**Comment by zephyrtronium** [comment]
`Sequence` has the method `fromBase`:

```io
io> 42 asBinary
00101010
io> 42 asBinary fromBase(2)
42
```

**Comment by vaartis** [comment]
Thank you. I guess it should maybe be mentioned somewhere, or something like that. Either way, good thing it does exist.

**Comment by stevedekorte** [comment]
> Thank you. I guess it should maybe be mentioned somewhere, or something like that. Either way, good thing it does exist.

Good idea. I'll try to add that to the docs for each of those two methods.

**Comment by stevedekorte** [comment]
I've updated the docs:
https://iolanguage.org/reference/index.html
Search for "Related methods".

Thanks for the suggestion vaartis.
